# Generated by Django 3.1.5 on 2021-01-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeUsername', models.CharField(max_length=30)),
                ('EmployeeTask', models.CharField(max_length=200)),
                ('TaskDate', models.DateField()),
            ],
        ),
    ]
